spring.application.name=Quick_Shop

server.port= 6667

# database configurations for connecting to mysql database
spring.datasource.url=jdbc:mysql://localhost:3306/Quick_Shop
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA and Hibernate Properties/Configurations
#This will show the sql queries running internally in console
spring.jpa.show-sql=true

#For automatically update database after every change
spring.jpa.hibernate.ddl-auto=update

#Tt converts the java data types into database data type
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect